language: ruby
cache:
  directories:
    - "./vendor/bundle"
    - "./.asset-cache"
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec middleman build
deploy:
  - provider: pages
    github-token: "$GITHUB_TOKEN"
    target-branch: dist
    local-dir: build
    name: pietbot
    email: hi+pietbot@pietvanzoen.com
    keep-history: true
    skip_cleanup: true
    verbose: true
    on:
      branch: master
env:
  global:
    secure: OLZ7WxVYkhwzuxVl+L5jQbBL5+rsw0DVtsd7s0nPqbGQz9PRb+sk6TAAeRFKpGPJtLC33tGrTrWiHkAKXFU8mhF+Q8fY/AutWxnYa1eK7p/wJnvhEnp2UupBVFnF8P8AV4ZU57SwlC+UZK31b5eOub//qvNcNoF052W8i26+3K8S+M5IhmqDcpWZSsXnuuuyQx84MqZkSovIY49pAD0stRTpqQoHdW7fz648tjVPPPnQasSZXrkVy6xE7JbclJUPmucESqIYixIkF2QTGf69HU7Y4UrTXxIn+31Qpa+6Hg80cvZW6pH2vJS3tI6FkY4VkzbjI05rVfo6GKKShE8pkiNkTupG1010U/3VldAa4PfA5eEi8CI1iPOey8hGv0qEd2ZGtaLXs2TuppHXJKV+QMzlU751xnNSS3T34B6/icrCR35CY/+lNYTSyuRmbXX9JE6HgFA8YLufeZp5tTiwqyRzk6srZ6+LFD3RcB66ta1dVk/w5x32XO1P0VcAiAK/1pb4t3RLJAyoTbE5DrROuD+oNzqpx+FXby7/ZvGtN18ufnbeG08mVByNzNqaZHIKJsWwJ4YlFRWtbE5o4pMKU2Wrjp8qNSQR0CFqqf4ISUGQAkUFDqe53uU1uzhbXR+OnGiKM6+6nxgk0uKktlXrX5wjj58aZHfKw7WkpL30/do=
