language: ruby
cache:
  directories:
    - ./vendor/bundle
    - ./.asset-cache
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec middleman build
deploy:
  - provider: pages
    github-token: "$GITHUB_TOKEN"
    target-branch: dist
    local-dir: build
    name: pietbot
    email: hi+pietbot@pietvanzoen.com
    keep-history: true
    skip_cleanup: true
    verbose: true
    on:
      branch: master
